# Generated by Django 5.2.9 on 2025-12-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='was_late',
        ),
    ]
