# Generated by Django 5.2.9 on 2025-12-15 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_history', to='estate.tenant')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['tenant', 'effective_from'], name='estate_tena_tenant__a1d84d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'effective_from'), name='unique_rent_per_tenant_per_month')],
            },
        ),
    ]
