# Generated by Django 5.2.9 on 2025-12-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_tenantrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g. 10.00 for 10%)', max_digits=5)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('effective_from',), name='unique_commission_rate_per_month')],
            },
        ),
    ]
