# Generated by Django 5.2.9 on 2025-12-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_commissionrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the expense (free‑form, e.g. Electricity bill, Repair work)', max_length=255),
        ),
    ]
