# Generated by Django 5.2.9 on 2025-12-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_expense_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
    ]
