# Generated by Django 5.2.9 on 2025-12-18 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_delete_salarypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='estate.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'effective_from'), name='unique_salary_per_employee_per_month')],
            },
        ),
    ]
