# Generated by Django 5.2.9 on 2025-12-24 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_employee_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='estate.property'),
        ),
    ]
