# Generated by Django 5.2.9 on 2025-12-25 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_alter_employee_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Set for employee-related expenses (e.g., Salary).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='estate.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_month',
            field=models.DateField(blank=True, help_text='Month this expense is booked to (first day of month).', null=True),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['property', 'date'], name='estate_expe_propert_f0eb89_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['property', 'expense_month'], name='estate_expe_propert_115a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['employee', 'expense_month'], name='estate_expe_employe_a56176_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('employee', 'expense_month', 'category'), name='unique_employee_expense_per_month_per_category'),
        ),
    ]
