# Generated by Django 5.2.9 on 2025-12-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_expense_employee_expense_expense_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='commission_source',
            field=models.OneToOneField(blank=True, help_text='Set only for rent collection commission; enforces one commission per rent payment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_expense', to='estate.rentpayment'),
        ),
    ]
