# Generated by Django 5.2.9 on 2025-12-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_expense_commission_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='commission_source',
        ),
    ]
